# Generated by Django 4.2.6 on 2023-11-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='advisor_end',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='advisor_start',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='birthday',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='child_birthday',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='День рождение ребенка'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='last_job_end',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='last_job_start',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='qualification_end',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='qualification_start',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата начала'),
        ),
    ]
