# Generated by Django 4.2.6 on 2023-12-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='edu_end',
            field=models.DateField(blank=True, null=True, verbose_name='Конец обучения'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='edu_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало обучения'),
        ),
    ]
