# Generated by Django 4.2.6 on 2023-11-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_cv_advisor_end_alter_cv_advisor_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='advisor_end',
            field=models.CharField(default=1, max_length=100, verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='advisor_start',
            field=models.CharField(default=1, max_length=100, verbose_name='Дата начала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='birthday',
            field=models.CharField(default=1, max_length=100, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='child_birthday',
            field=models.CharField(default=1, max_length=100, verbose_name='День рождени'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='last_job_end',
            field=models.CharField(default=1, max_length=100, verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='last_job_start',
            field=models.CharField(default=1, max_length=100, verbose_name='Дата начала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='qualification_end',
            field=models.CharField(default=1, max_length=100, verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='qualification_start',
            field=models.CharField(default=1, max_length=100, verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
