# Generated by Django 4.2.6 on 2023-11-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_cv_abroad_start_alter_cv_advisor_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='abroad_end',
            field=models.DateField(default=False, verbose_name='Дата окончания'),
        ),
    ]
