# Generated by Django 4.2.6 on 2023-12-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_cv_user_alter_readycv_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='abroad_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='abroad_start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='acq_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='acq_start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='advisor_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='advisor_start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='birthday',
            field=models.CharField(max_length=255, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='child_birthday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='День рождение'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='edu_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Конец обучения'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='edu_start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Начало обучения'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='last_job_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='last_job_start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='qualification_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='qualification_start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата начала'),
        ),
    ]
