# Generated by Django 4.2.6 on 2023-12-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_cv_abroad_end_alter_cv_abroad_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
