# Generated by Django 4.2.6 on 2023-12-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_cv_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='test_year',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Год'),
        ),
    ]
