# Generated by Django 4.2.6 on 2023-11-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_cv_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='interested_yes',
            field=models.BooleanField(default=False, verbose_name='Готовы ли рассматривать другие позиции в Kyrgyz Concept?'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='interested_position',
            field=models.CharField(max_length=250, verbose_name='Укажите интересные для вас позиции'),
        ),
    ]
