# Generated by Django 4.2.6 on 2023-12-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_cv_internship_salary_alter_cv_job_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='google_docs',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='google_presentation',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='google_tables',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='prezi',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='touch_typing',
        ),
    ]
