# Generated by Django 4.2.6 on 2023-12-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_cv_google_docs_remove_cv_google_presentation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='laptop',
        ),
    ]
