# Generated by Django 4.2.6 on 2023-12-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_cv_google_docs_cv_google_presentation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='google_docs',
            field=models.BooleanField(default=False, verbose_name='Google Документы'),
        ),
    ]
