# Generated by Django 4.2.6 on 2023-12-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_cv_google_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='google_docs',
            field=models.BooleanField(default=False, verbose_name='Google Документы'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='google_presentation',
            field=models.BooleanField(default=False, verbose_name='Google Презентации'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='google_tables',
            field=models.BooleanField(default=False, verbose_name='Google Таблицы'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='laptop',
            field=models.BooleanField(default=False, verbose_name='Имеется ли у Вас ноутбук?'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='prezi',
            field=models.BooleanField(default=False, verbose_name='Prezi'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='touch_typing',
            field=models.BooleanField(default=False, verbose_name='Слепая печать'),
        ),
    ]
