# Generated by Django 4.2.6 on 2023-12-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_cv_google_docs_alter_cv_google_presentation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='laptop',
            field=models.BooleanField(default=False, null=True, verbose_name='Имеется ли у Вас ноутбук?'),
        ),
    ]
