# Generated by Django 4.2.6 on 2023-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_alter_cv_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='acq_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
    ]
