# Generated by Django 4.2.6 on 2023-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('descriptions', models.TextField(verbose_name='Описание сайта')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон номер')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('tripadvisor', models.URLField(blank=True, null=True, verbose_name='Tripadvisor URL')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
            ],
            options={
                'verbose_name': 'Основная настройка',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
