# Generated by Django 4.2.6 on 2023-12-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.URLField(verbose_name='Логотип'),
        ),
    ]
